name: Call apprunner.sh
description: Call the apprunner.sh with proper arguments
inputs:
  operation:
    description: The operation params to the script
    required: true
  aws-access-key-id:
    description: AWS access key id
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true
  aws-region:
    description: AWS region
    required: false
    default: ap-northeast-1
  github-connection-arn:
    description: GitHub connection ARN from the AppRunner console
    required: false
    default: ""
  ecr-repository-name:
    description: The name of the private ECR repository
    required: false
    default: ""
  ecr-repository-url:
    description: The URL of the ECR repository
    required: false
    default: ""
  should-use-ecr:
    description: Should use the ECR or the GitHub directly
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - env:
        ECR_REPOSITORY_NAME: ${{ inputs.ecr-repository-name }}
        GITHUB_CONNECTION_ARN: ${{ inputs.github-connection-arn }}
        AWS_REGION: ${{ inputs.aws-region }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
        OPERATION: ${{ inputs.operation }}
        ECR_REPOSITORY_URL: ${{ inputs.ecr-repository-url }}
        SHOULD_USE_ECR: ${{ inputs.should-use-ecr }}
      run: |
        echo "aws_region=$AWS_REGION \
        environment=$(basename $GITHUB_REF) \
        github_connection_arn=$GITHUB_CONNECTION_ARN \
        github_code_repo_url=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY \
        ecr_repo_name=$ECR_REPOSITORY_NAME" \
        ecr_repo_url=$ECR_REPOSITORY_URL \
        github_code_branch=${GITHUB_REF#"refs/heads/"} \
        should_use_ecr=$SHOULD_USE_ECR \
        > .apprunner.env
        ./apprunner.sh $OPERATION
      shell: bash
      working-directory: ./deploy/scripts
